/*
  # Create Sales Sheets Table

  1. New Tables
    - `sales_sheets` - Daily sales summaries generated by moderators
      - `id` (uuid, primary key)
      - `store_id` (uuid, references stores)
      - `date` (date, the day being reported)
      - `total_sales` (numeric, auto-calculated)
      - `total_buy_cost` (numeric, auto-calculated)
      - `net_profit` (numeric, auto-calculated)
      - `total_dollar_cost` (numeric, input by moderator)
      - `generated_by` (uuid, references profiles)
      - `created_at` (timestamptz)

  2. Indexes
    - store_id, date for daily queries

  3. Security
    - Enable RLS on `sales_sheets` table
    - Moderators can create for their store
    - Moderators can view their store's sheets
    - Admins can view all sheets
*/

CREATE TABLE IF NOT EXISTS sales_sheets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  store_id uuid NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  date date NOT NULL,
  total_sales numeric NOT NULL DEFAULT 0,
  total_buy_cost numeric NOT NULL DEFAULT 0,
  net_profit numeric NOT NULL DEFAULT 0,
  total_dollar_cost numeric NOT NULL DEFAULT 0,
  generated_by uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now(),
  UNIQUE(store_id, date)
);

CREATE INDEX IF NOT EXISTS idx_sales_sheets_store_date ON sales_sheets(store_id, date);
CREATE INDEX IF NOT EXISTS idx_sales_sheets_store_id ON sales_sheets(store_id);
CREATE INDEX IF NOT EXISTS idx_sales_sheets_date ON sales_sheets(date);

ALTER TABLE sales_sheets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Moderators can create sales sheets for their store"
  ON sales_sheets FOR INSERT
  TO authenticated
  WITH CHECK (
    store_id = (SELECT store_id FROM profiles WHERE id = auth.uid())
    AND (SELECT role FROM profiles WHERE id = auth.uid()) IN ('moderator', 'admin')
  );

CREATE POLICY "Moderators can view their store sales sheets"
  ON sales_sheets FOR SELECT
  TO authenticated
  USING (
    store_id = (SELECT store_id FROM profiles WHERE id = auth.uid())
    OR (SELECT role FROM profiles WHERE id = auth.uid()) = 'admin'
  );

CREATE POLICY "Moderators can update their store sales sheets"
  ON sales_sheets FOR UPDATE
  TO authenticated
  USING (
    store_id = (SELECT store_id FROM profiles WHERE id = auth.uid())
    AND (SELECT role FROM profiles WHERE id = auth.uid()) IN ('moderator', 'admin')
  )
  WITH CHECK (
    store_id = (SELECT store_id FROM profiles WHERE id = auth.uid())
    AND (SELECT role FROM profiles WHERE id = auth.uid()) IN ('moderator', 'admin')
  );

CREATE POLICY "Admins can view all sales sheets"
  ON sales_sheets FOR SELECT
  TO authenticated
  USING ((SELECT role FROM profiles WHERE id = auth.uid()) = 'admin');